name: Push dev to Website1 S3

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      # Website1 Account
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials from Website1 account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::843083765050:role/GitHub-Web-Site
          aws-region: us-east-1
      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 sync html/* s3://eric-milan-dev
